const TOURNAMENTS = [
  {
    id:"duel_sun", year:1977, eraClass:"era-1977", lbClass:"lb-1977",
    name:"The Duel in the Sun",
    course:"Turnberry — Ailsa Course", country:"Ayrshire, Scotland",
    type:"major", badge:"badge-major", days:4,
    lore:"Two men, three shots, the finest Open Championship ever played. Watson shot 65-65 in the final two rounds. Nicklaus matched him almost stroke for stroke. Nobody else mattered.",
    players:[
      { id:"watson", name:"Tom Watson", abbr:"WAT",
        desc:"The man who won. 268 total — 8 under. Nerveless over four days.",
        wound:"Has to beat Nicklaus on every hole to justify the legend.",
        historicalScores:[-1,-3,-5,-8] },
      { id:"nicklaus", name:"Jack Nicklaus", abbr:"NIC",
        desc:"Shot 65-66 in rounds 3 and 4. Still lost by a shot. The bear in full.",
        wound:"The greatest player in the world and still not quite enough.",
        historicalScores:[0,-2,-5,-7] }
    ],
    field:[
      {name:"Hubert Green",   scores:[0,-2,-4,-5]},
      {name:"Lee Trevino",    scores:[1,-1,-3,-4]},
      {name:"Ben Crenshaw",   scores:[2,0,-1,-2]},
      {name:"Arnold Palmer",  scores:[3,1,0,0]},
    ],
    holes:[
      {id:"t1",  name:"1st — Ailsa",        par:4,yards:350, hazard:"rough both sides",
       lore:"The opening hole with Turnberry lighthouse visible. Sets the tone immediately.",
       incidents:["Watson and Nicklaus both parred the 1st together on Day 4, acknowledging the gallery, setting the tone for golf's greatest final round."],
       events:["first_tee_announce"], pressureRating:1},
      {id:"t15", name:"15th — Ca' Canny",   par:3,yards:209, hazard:"deep rough, wind off the sea",
       lore:"The par 3 where the sea wind becomes the invisible third player.",
       incidents:["Watson made birdie here on Day 4, briefly going two ahead. Nicklaus answered immediately."],
       events:["wind_gusts","gallery_distraction"], pressureRating:2,
       modifiers:{thresholdAdd:1,atmosphereNote:"The sea wind off the Firth of Clyde is unreadable. Club selection is approximately a guess. The invisible third player is in full effect."}},
      {id:"t18", name:"18th — Ailsa Home",  par:4,yards:431, hazard:"rough, gallery, history",
       lore:"Watson and Nicklaus shook hands on this green having played the greatest final round in Open Championship history.",
       incidents:["Nicklaus made birdie. Watson made birdie. Watson won by a single shot.","The gallery stood as both men walked up 18 together."],
       events:["historic_moment","gallery_enormous"], pressureRating:3,
       modifiers:{atmosphereNote:"Turnberry 18 in 1977 — both men know they are walking into history. The gallery has understood this for three hours."}},
    ]
  },
  {
    id:"tiger_2005", year:2005, eraClass:"era-2005", lbClass:"lb-2005",
    name:"Tiger at Augusta",
    course:"Augusta National", country:"Georgia, USA",
    type:"major", badge:"badge-major", days:4,
    lore:"The chip-in on 16. The ball balanced on the lip. The Nike swoosh visible to 200 million people. Golf's defining single shot. But a complete tournament still needed winning.",
    players:[
      { id:"tiger", name:"Tiger Woods", abbr:"TWD",
        desc:"Won by one shot over DiMarco. The chip on 16 is the shot.",
        wound:"The weight of expectation is total. Perfection is the baseline.",
        historicalScores:[-2,-4,-8,-12] },
      { id:"dimarco", name:"Chris DiMarco", abbr:"CDM",
        desc:"Pushed Tiger to a playoff then lost. The worthy foil.",
        wound:"The chip-in cost him a major. He played beautifully.",
        historicalScores:[-1,-3,-7,-12] }
    ],
    field:[
      {name:"Retief Goosen", scores:[-1,-2,-5,-8]},
      {name:"Luke Donald",   scores:[0,-1,-4,-7]},
      {name:"Mike Weir",     scores:[1,0,-2,-5]},
      {name:"Vijay Singh",   scores:[2,1,-1,-3]},
    ],
    holes:[
      {id:"a12", name:"12th — Golden Bell",  par:3,yards:155, hazard:"Rae's Creek front, bunkers rear",
       lore:"The most dangerous par 3 in major golf. Wind swirls and cannot be predicted. Every year it destroys someone.",
       incidents:["In 1992 Fred Couples' ball stopped on the downslope, not rolling into the creek — replayed thousands of times since.","Tiger has made birdie on 12 more often than any other active player."],
       events:["wind_unpredictable","gallery_silent_green"], pressureRating:3,
       modifiers:{thresholdAdd:1,atmosphereNote:"Amen Corner — the wind swirls from three directions and the fourth is a lie. Club selection at 12 is genuinely a guess for any player, any day."}},
      {id:"a13", name:"13th — Azalea",       par:5,yards:510, hazard:"Rae's Creek in front of green",
       lore:"The great risk/reward hole of the back nine. Eagles here are tournament-winning moves.",
       incidents:["Seve eagled here in 1980, launching his first Masters win.","Tiger laid up three times in a row in 2001, then eagled on Sunday."],
       events:["creek_decision"], pressureRating:2,
       modifiers:{atmosphereNote:"The eagle decision at 13 is the Masters' central risk/reward moment. Go for it and win or lose the tournament in one shot."}},
      {id:"a16", name:"16th — Redbud",       par:3,yards:170, hazard:"water left, slope runs toward pin",
       lore:"Sunday 2005. Tiger's chip from the rough above the hole. Ball balanced on the lip for three seconds. Nike swoosh showing. Then fell.",
       incidents:["The chip-in on 16 in 2005 is arguably the most famous single shot in Masters history.","The gallery reaction has been described as the loudest noise ever heard at Augusta."],
       events:["chip_from_rough"], pressureRating:3,
       modifiers:{atmosphereNote:"Hole 16 at Augusta carries the memory of the 2005 chip-in. Every shot here is played in the ghost of that moment. The gallery remembers before you've hit."}},
    ]
  },
  {
    id:"medinah_2012", year:2012, eraClass:"era-2012", lbClass:"lb-2012",
    name:"The Miracle at Medinah",
    course:"Medinah Country Club", country:"Illinois, USA",
    type:"ryder", badge:"badge-ryder", days:3,
    lore:"Europe 10–6 down going into Sunday singles. Poulter had kept Europe alive Saturday night with five birdies in a row on the last five holes. What followed was a miracle. Or an American collapse.",
    players:[
      { id:"poulter", name:"Ian Poulter", abbr:"IPC",
        desc:"Five birdies on the last five Saturday holes. The heart of Europe. Ryder Cup animal.",
        wound:"The weight of a continent. Personal mythology being written in real time.",
        historicalScores:[0,-3,-7],
        matchPlayDays:[
          { opponent:"Keegan Bradley / Phil Mickelson", opponentHoleScores:[3,4,4] },
          { opponent:"Tiger Woods / Steve Stricker",    opponentHoleScores:[3,5,4] },
          { opponent:"Webb Simpson",                    opponentHoleScores:[4,4,5] },
        ]},
      { id:"garcia", name:"Sergio Garcia", abbr:"SGC",
        desc:"Quietly brilliant across all three days. Won his Sunday singles comfortably.",
        wound:"Always performing against the noise of expectation. Quieter than his reputation.",
        historicalScores:[-1,-2,-5],
        matchPlayDays:[
          { opponent:"Bubba Watson / Webb Simpson",   opponentHoleScores:[3,5,5] },
          { opponent:"Jason Dufner / Zach Johnson",   opponentHoleScores:[4,4,4] },
          { opponent:"Bubba Watson",                  opponentHoleScores:[3,4,5] },
        ]},
      { id:"rose", name:"Justin Rose", abbr:"JRO",
        desc:"Won his Sunday singles point on the 18th. Part of the miracle.",
        wound:"Composed under pressure that would unravel other people.",
        historicalScores:[0,-1,-4],
        matchPlayDays:[
          { opponent:"Phil Mickelson / Keegan Bradley", opponentHoleScores:[4,4,5] },
          { opponent:"Jason Dufner / Zach Johnson",     opponentHoleScores:[3,5,4] },
          { opponent:"Phil Mickelson",                  opponentHoleScores:[3,4,4] },
        ]},
    ],
    field:[
      {name:"Francesco Molinari", scores:[0,-1,-3]},
      {name:"Rory McIlroy",       scores:[1,0,-2]},
      {name:"Lee Westwood",       scores:[1,1,-1]},
      {name:"Luke Donald",        scores:[0,0,-2]},
    ],
    holes:[
      {id:"m2",  name:"2nd — Lake Kadijah",  par:3,yards:189, hazard:"Lake Kadijah virtually surrounds the green",
       lore:"Water on all sides. The galleries are enormous and the USA is very, very loud.",
       incidents:["Several European players found water here in team matches, gifting points to the home side."],
       events:["crowd_hostile","lake_stare"], pressureRating:3,
       modifiers:{thresholdAdd:1,compCost:1,atmosphereNote:"Lake Kadijah virtually surrounds the green. The American crowd at Medinah in 2012 was 20,000 people and none of them wanted Europe to succeed."}},
      {id:"m17", name:"17th — Lakeside",     par:4,yards:424, hazard:"Lake Kadijah right, bunkers left",
       lore:"On Sunday, this hole changed the scoreboard six times. The Ryder Cup lived and died here.",
       incidents:["Poulter made birdie here in Saturday fourballs. The American crowd went completely silent."],
       events:["scoreboard_drama"], pressureRating:3,
       modifiers:{compCost:1,atmosphereNote:"Medinah 17 on Sunday singles — the leaderboard is moving every ninety seconds. Every shot carries the weight of the entire scoreboard."}},
      {id:"m18", name:"18th — Closing",      par:4,yards:441, hazard:"bunkers, closing gallery, the weight of history",
       lore:"Martin Kaymer holed the winning putt on 18 to seal the Cup for Europe. The silence from 20,000 Americans was profound.",
       incidents:["Kaymer's putt on 18 completed the most improbable comeback in Ryder Cup history.","Poulter was already crying before the ball fell."],
       events:["ryder_climax"], pressureRating:3,
       modifiers:{compCost:1,atmosphereNote:"Medinah 18 — Kaymer's putt lives here. The gallery of 20,000 Americans went completely silent when it dropped. History is visible from this green."}},
    ]
  },
  {
    id:"vandervelde_1999", year:1999, eraClass:"era-1999", lbClass:"lb-1999",
    name:"Van de Velde's Carnoustie",
    course:"Carnoustie — Championship Links", country:"Angus, Scotland",
    type:"collapse", badge:"badge-collapse", days:4,
    lore:"Jean Van de Velde stood on the 18th tee of the final round needing only a double bogey to win The Open Championship. He made seven. This is the game where you try not to do that.",
    players:[
      { id:"vandervelde", name:"Jean Van de Velde", abbr:"JVV",
        desc:"Led by three with one hole to play. What followed defies analysis.",
        wound:"The universe of what could have been. Three shots clear. One hole.",
        historicalScores:[-4,-7,-10,-9] },
      { id:"lawrie", name:"Paul Lawrie", abbr:"PLW",
        desc:"Started Round 4 ten shots back. Won in a playoff. Scotland's accidental champion.",
        wound:"Nobody expected this. Including him, if he's honest.",
        historicalScores:[-1,-3,-6,-9] }
    ],
    field:[
      {name:"Justin Leonard",  scores:[-2,-4,-7,-9]},
      {name:"Tiger Woods",     scores:[0,-2,-5,-7]},
      {name:"Davis Love III",  scores:[1,-1,-3,-6]},
      {name:"Craig Parry",     scores:[2,0,-2,-5]},
    ],
    holes:[
      {id:"c6",  name:"6th — Long",     par:5,yards:578, hazard:"cross bunkers, rough everywhere",
       lore:"The longest hole on the course. Van de Velde birdied this in Round 4, extending his lead. Feeling good.",
       incidents:["Van de Velde played this hole beautifully in the final round. His problems were elsewhere."],
       events:["false_security"], pressureRating:1},
      {id:"c17", name:"17th — Island",  par:4,yards:459, hazard:"Barry Burn crosses the fairway",
       lore:"The Barry Burn cuts across the fairway. Everyone knows about 18, but 17 sets the stage.",
       incidents:["The burn punishes the careless and rewards those who take their medicine."],
       events:["burn_warning"], pressureRating:2,
       modifiers:{thresholdAdd:1,atmosphereNote:"The Barry Burn on 17 is the warning. It is telling you something about 18. The question is whether you are listening."}},
      {id:"c18", name:"18th — Home",    par:4,yards:499, hazard:"Barry Burn crosses twice. Grandstand. Rough. The burn again.",
       lore:"Driver over the grandstand. Second hit the rail, back to thick rough. Third into the burn. Shoes off. Dropped. Bunker. Seven. Lost in a playoff.",
       incidents:[
         "Van de Velde hit his drive wildly right — it went over the grandstand and came back.",
         "His second shot struck the grandstand rail and ricocheted into thick rough.",
         "He attempted to play from the rough over the burn. It landed in the water.",
         "He stood in the Barry Burn in his socks, considering playing from the water.",
         "He eventually took a drop, chipped into a bunker, and made seven.",
         "Paul Lawrie won the three-man playoff. Van de Velde was never the same."
       ],
       events:["vandervelde_18th"], pressureRating:5, collapseSequence:true,
       modifiers:{thresholdAdd:2,compCost:2,atmosphereNote:"Carnoustie 18 — the Barry Burn crosses the fairway twice. The grandstand is in play. The rough is impenetrable. Van de Velde needed a double bogey to win The Open. He made seven. This hole has a memory and it is not kind."}},
    ]
  },
  {
    id:"muirfield_1972", year:1972, eraClass:"era-1972", lbClass:"lb-1972",
    name:"Trevino's Chip — Muirfield 1972",
    course:"Muirfield", country:"East Lothian, Scotland",
    type:"major", badge:"badge-major", days:4,
    lore:"Jacklin led. Trevino was finished. On the 17th, Trevino chipped in from off the green for par. Jacklin three-putted. Trevino won. Jacklin never won a major again.",
    players:[
      { id:"trevino", name:"Lee Trevino", abbr:"LTV",
        desc:"Merry Mex. Sharp, funny, relentless competitor. Won it by one.",
        wound:"The chip on 17 was either genius or pure chaos. Trevino says chaos.",
        historicalScores:[-1,-3,-6,-8] },
      { id:"jacklin", name:"Tony Jacklin", abbr:"TAJ",
        desc:"Led going into 17. Three-putted after Trevino chipped in. Collapsed. Never recovered.",
        wound:"The defining psychological wound of a career. Permanently marks everything after.",
        historicalScores:[0,-2,-7,-7] }
    ],
    field:[
      {name:"Jack Nicklaus",      scores:[-1,-3,-5,-6]},
      {name:"Doug Sanders",       scores:[1,-1,-3,-5]},
      {name:"Peter Oosterhuis",   scores:[2,0,-2,-4]},
      {name:"Bert Yancey",        scores:[2,1,0,-3]},
    ],
    holes:[
      {id:"mu9",  name:"9th — Mid",       par:5,yards:504, hazard:"fairway bunkers, cross wind",
       lore:"The pivotal par 5. Birdies here can create or protect a lead going into the back nine.",
       incidents:["Trevino made birdie here in all four rounds. Jacklin dropped a shot in Round 3."],
       events:["cross_wind","birdie_opportunity"], pressureRating:1},
      {id:"mu14", name:"14th — Peesweep", par:4,yards:449, hazard:"deep rough, bunkers",
       lore:"Long par 4 where the psychological pressure begins to accumulate on final day.",
       incidents:["Jacklin was still in control here in Round 4. His lead was intact. What happened next was not his fault."],
       events:["mental_pressure"], pressureRating:2,
       modifiers:{atmosphereNote:"The pressure at 14 is not physical. The hole is playing normally. Everything else is not."}},
      {id:"mu17", name:"17th — Road Hole",par:5,yards:542, hazard:"road right, rough, history",
       lore:"Trevino chipped in for par from off the green. Jacklin three-putted for bogey watching it happen. The Open Championship changed hands on this green.",
       incidents:[
         "Trevino's fourth shot from off the green was rolling past the hole when it struck the flagstick and dropped in for par.",
         "Jacklin, watching this happen, three-putted from fifteen feet.",
         "The psychological damage to Jacklin was described by him as permanent. He said he never fully recovered his nerve."
       ],
       events:["trevino_moment"], pressureRating:4,
       modifiers:{thresholdAdd:1,compCost:2,atmosphereNote:"Muirfield 17 — Trevino's chip-in for par happened on this green. Jacklin three-putted watching it. The Open Championship changed hands here. The hole remembers this."}},
    ]
  }
];

if (typeof module !== 'undefined') module.exports = { TOURNAMENTS };
