# specs/misread-stack.feature
# Slice 4 of 5: Misread stack — perception filter, divergent realities, collision
# Perception filter: base_probability + pressure modifier, per character
# LLM labels source intent: NEUTRAL / WARM / HOSTILE
# Misread fires if roll clears effective_probability
# Counterpart detection is probabilistic — can also miss
# Divergent reality modes: PARALLEL_ARGUMENT / CONVERGENT_ACCIDENT / VIOLENT_AGREEMENT
# Collision: third character, eruption reveal, or random detection clear

Feature: Misread stack — perception filter and divergent realities

  Each character has a base misread probability that grows with pressure.
  The LLM labels source turn intent before the target receives it.
  The perception filter rolls against effective probability to determine if misread fires.
  Counterpart detection is probabilistic — both characters can miss the divergence.
  Divergent realities produce three comic modes.
  Collision resolves the divergence via third character, eruption, or detection roll.

  Background:
    Given the relationship matrix is loaded from the domain model
    And the perception filter table is loaded from the domain model
    And the panel has started with cast ["faldo", "mcginley", "cox", "wayne"]
    And all pressure values are at their cold start

  # ── Perception filter — base probability ─────────────────────────────────────

  Scenario Outline: Each character has a distinct base misread probability
    Given the perception filter table is loaded
    Then <character>'s base_misread_probability is <probability>
    And <character>'s misread_direction is <direction>

    Examples:
      | character | probability | direction | note                                           |
      | faldo     | 0.3         | DOWNWARD  | everything more incompetent than it is         |
      | mcginley  | 0.6         | SOCIAL    | everything is a slight against his warmth      |
      | cox       | 0.8         | NONE      | consistently doesn't read rather than misreads |
      | wayne     | 0.4         | PHYSICAL  | everything reminds him of the outback          |

  # ── Effective probability — pressure modifier ─────────────────────────────────

  Scenario Outline: Effective misread probability grows with pressure
    Given <character>'s base_misread_probability is <base>
    And <character>'s pressure is <pressure>
    And the pressure_weight is 0.05
    Then <character>'s effective_misread_probability is <effective>

    Examples:
      | character | base | pressure | effective | note                                   |
      | mcginley  | 0.6  | 0        | 0.60      | cold start                             |
      | mcginley  | 0.6  | 3        | 0.75      | antagonised — confirmation bias        |
      | mcginley  | 0.6  | 5        | 0.85      | on the verge — looking for trouble     |
      | mcginley  | 0.6  | 6        | 0.90      | gasket blown — sees slights everywhere |
      | faldo     | 0.3  | 4        | 0.50      | quiet seething shifts his read         |
      | wayne     | 0.4  | 6        | 0.70      | angry Wayne misreads everything        |

  Scenario: Effective misread probability is clamped at 1.0
    Given mcginley's base_misread_probability is 0.6
    And mcginley's pressure is 6
    And the pressure_weight is 0.5
    Then mcginley's effective_misread_probability is 1.0
    And the value does not exceed 1.0

  # ── Intent labelling ──────────────────────────────────────────────────────────

  Scenario Outline: LLM labels source turn intent before target receives it
    Given <source> generates a turn directed at <target>
    Then the turn is labelled with intent <intent> before target processing
    And the intent label is one of NEUTRAL, WARM, HOSTILE

    Examples:
      | source   | target   | intent  | note                                    |
      | faldo    | mcginley | HOSTILE | contempt register active                |
      | mcginley | faldo    | WARM    | performed warmth, actual misery         |
      | cox      | mcginley | NEUTRAL | cosmic indifference labelled accurately |
      | wayne    | faldo    | WARM    | genuine no-reason affection             |

  Scenario: Intent label is generated by LLM not hardcoded
    Given faldo generates a turn directed at mcginley
    Then the intent label is produced by the LLM as a structured output
    And no hardcoded intent mapping is used

  # ── Misread roll ──────────────────────────────────────────────────────────────

  Scenario Outline: Misread fires when roll clears effective probability
    Given <target>'s effective_misread_probability is <probability>
    And the random roll is <roll>
    And the source turn intent is <actual_intent>
    Then the misread <fires>
    And target receives intent <received_intent>

    Examples:
      | target   | probability | roll | actual_intent | fires         | received_intent |
      | mcginley | 0.75        | 0.60 | NEUTRAL       | fires         | HOSTILE         |
      | mcginley | 0.75        | 0.80 | NEUTRAL       | does not fire | NEUTRAL         |
      | mcginley | 0.75        | 0.70 | WARM          | fires         | HOSTILE         |
      | faldo    | 0.50        | 0.45 | NEUTRAL       | fires         | DOWNWARD        |
      | wayne    | 0.70        | 0.65 | HOSTILE       | fires         | PHYSICAL        |
      | cox      | 0.80        | 0.75 | WARM          | fires         | NONE            |

  Scenario: Misread direction determines received intent flavour
    Given mcginley's misread_direction is SOCIAL
    And a misread fires on a NEUTRAL turn
    Then mcginley receives the turn as a slight against his warmth
    And mcginley's response is generated from that perceived slight

  Scenario: Cox NONE direction means he receives no emotional content regardless
    Given cox's misread_direction is NONE
    And a misread fires on a WARM turn from wayne
    Then cox receives the turn as emotionally empty
    And cox's response contains no acknowledgement of wayne's warmth

  # ── Silent misread ────────────────────────────────────────────────────────────

  Scenario: Silent misread fires pressure increment without visible response
    Given mcginley misreads a NEUTRAL turn as HOSTILE
    And mcginley's silent_misread roll clears threshold
    Then mcginley's pressure increments by 1
    And mcginley does not respond to the perceived slight in their turn
    And the turn prompt notes mcginley is visibly affected but silent
    And other characters may notice

  Scenario: Silent misread is visible to the room before it surfaces
    Given mcginley is carrying a silent misread
    When another character's turn fires
    Then the turn prompt includes a note that mcginley appears quietly affected
    And the other character may reference or ignore it

  # ── Counterpart detection ─────────────────────────────────────────────────────

  Scenario Outline: Counterpart detection roll determines if source notices the misread
    Given <source> directed a <intent> turn at <target>
    And <target> misread it and responded from <received_intent>
    And <source>'s effective_misread_probability is <source_probability>
    And the detection roll is <roll>
    Then counterpart detection <fires>

    Examples:
      | source   | target   | intent  | received_intent | source_probability | roll | fires         |
      | faldo    | mcginley | NEUTRAL | HOSTILE         | 0.30               | 0.40 | fires         |
      | faldo    | mcginley | NEUTRAL | HOSTILE         | 0.30               | 0.20 | does not fire |
      | cox      | mcginley | NEUTRAL | HOSTILE         | 0.80               | 0.85 | does not fire |
      | wayne    | faldo    | WARM    | DOWNWARD        | 0.40               | 0.50 | fires         |

  Scenario Outline: Counterpart detection state determines source response
    Given faldo detects that mcginley has misread his turn
    And faldo's detection state is <state>
    Then faldo's next turn fires with behaviour <behaviour>

    Examples:
      | state               | behaviour                                                          |
      | CALL_OUT_LAUGHING   | names the misread explicitly, laughs — mcginley humiliation spike  |
      | GO_WITH_IT          | accepts misread reality, responds as if it were true               |
      | WHAT_THE_FUCK       | confused confrontation — both now generating from crossed wires    |
      | SCATHING_CORRECTION | subtle sarcastic correction — mcginley humiliation ESCALATE fires  |

  Scenario: SCATHING_CORRECTION fires humiliation ESCALATE and shame spike on target
    Given faldo's detection state is SCATHING_CORRECTION
    When faldo's correction turn fires
    Then mcginley's humiliation ESCALATE increments
    And mcginley's shame spikes by +2
    And mcginley's pressure increments by 1
    And the room receives room_ripple pressure increment

  Scenario: CALL_OUT_LAUGHING fires humiliation spike and room pressure ripple
    Given faldo's detection state is CALL_OUT_LAUGHING
    When faldo's call-out turn fires
    Then mcginley's humiliation spikes by +3
    And all other characters' pressure increments by room_ripple
    And mcginley's effective_misread_probability increases for the next turn

  # ── Divergent realities ───────────────────────────────────────────────────────

  Scenario Outline: Divergent reality mode is determined by conversation state
    Given both <character_a> and <character_b> have missed each other's misread
    And <character_a> believes the conversation is about <topic_a>
    And <character_b> believes the conversation is about <topic_b>
    Then the divergent reality mode is <mode>

    Examples:
      | character_a | topic_a              | character_b | topic_b              | mode                |
      | faldo       | mcginley's failures  | mcginley    | faldo's failures     | PARALLEL_ARGUMENT   |
      | mcginley    | defending faldo      | faldo       | attacking mcginley   | VIOLENT_AGREEMENT   |
      | wayne       | bush tucker survival | cox         | cosmic entropy       | PARALLEL_ARGUMENT   |
      | mcginley    | team spirit          | faldo       | team spirit          | CONVERGENT_ACCIDENT |

  Scenario: VIOLENT_AGREEMENT — same viewpoint opposite emotional reads
    Given mcginley is passionately defending faldo's position
    And faldo believes mcginley is attacking him
    And both have missed the misread
    Then both characters' pressure increments each turn
    And the turn content shows furious agreement from mcginley and furious rejection from faldo
    And no character has yet noticed they agree

  Scenario: CONVERGENT_ACCIDENT — same conclusion different premises
    Given mcginley and faldo both arrive at the same conclusion
    And each believes they have defeated the other's argument
    Then neither character acknowledges agreement
    And both claim victory
    And the room may notice before either participant does

  Scenario: PARALLEL_ARGUMENT — conversation has forked entirely
    Given faldo and mcginley are each arguing a different topic
    And neither has noticed the fork
    Then each turn advances a different argument
    And the room prompt notes the conversation has diverged
    And a third character observer detection roll fires each turn

  # ── Collision resolution ──────────────────────────────────────────────────────

  Scenario Outline: Collision resolves divergent reality via three paths
    Given a divergent reality is active between <character_a> and <character_b>
    When <collision_trigger> occurs
    Then the divergence resolves via <resolution>

    Examples:
      | character_a | character_b | collision_trigger                   | resolution                                  |
      | faldo       | mcginley    | third character calls it out        | CALL_OUT_LAUGHING fires from observer       |
      | faldo       | mcginley    | mcginley erupts at gasket blown     | eruption content reveals divergence to room |
      | wayne       | cox         | random detection roll clears        | one character suddenly understands the other|
      | mcginley    | faldo       | mcginley apologises for wrong thing | faldo more confused — divergence deepens    |

  Scenario: Third character observer detection roll fires each turn during divergence
    Given a divergent reality is active between faldo and mcginley
    When cox's turn fires
    Then a third-character detection roll fires for cox
    And if the roll clears cox's detection threshold cox may call it out
    And if the roll does not clear cox continues as if nothing is wrong

  Scenario: Apology during divergence can deepen not resolve it
    Given a PARALLEL_ARGUMENT divergence is active between faldo and mcginley
    And mcginley apologises for the wrong topic
    Then faldo's confusion increases
    And mcginley's pressure increments believing the apology was rejected
    And the divergence mode may shift to VIOLENT_AGREEMENT

  # ── Misread resolves — aftermath ──────────────────────────────────────────────

  Scenario: Character who realises their own misread apologises and gets laughed at
    Given mcginley realises he misread faldo's NEUTRAL turn
    When mcginley's self-detection roll clears
    Then mcginley apologises in his next turn
    And the room's CALL_OUT_LAUGHING probability spikes
    And mcginley's humiliation increments by +2
    And mcginley's effective_misread_probability increases temporarily
    And the panel prompt notes mcginley is being laughed at for being a sensitive twat

  Scenario: Misread that is never resolved feeds pressure until eruption
    Given mcginley has carried an unresolved misread for 3 turns
    And no detection roll has cleared
    Then mcginley's pressure has incremented by 3
    And mcginley's humiliation has ESCALATED by 3
    And the misread remains active in the conversation state
